name: Setup python
description: "Common setup for installing dependencies"

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          python-version: 3.13
      - name: Setup a local virtual environment
        shell: bash
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - run: poetry install
        shell: bash
      - run: sudo apt-get update
        shell: bash
      - run: sudo apt-get install git-crypt
        shell: bash
      - run: echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt.key
        shell: bash
      - run: git-crypt unlock ./git-crypt.key
        shell: bash
